### ISSUE TITLE
Possible skewing of core-hour results

### ISSUE THREAD

**Issue by ghost** [Picovoice/speaker-diarization-benchmark#2]
Heya, I was browsing around and noticed that the results for pyannote were particularly bad.

Pyannote has a bug when it is given a path to a file.
To get proper performance for it, you could do something like this:

```python
import torchaudio
def diarization(self, path: str) -> "Annotation":
    waveform, sample_rate = torchaudio.load(path)
    return self._pretrained_pipeline({"waveform": waveform, "sample_rate": sample_rate)
```
The code is from memory and I can't guarantee it's correct. The gist is that you need to provide the data from the file rather than the filename.

https://github.com/Picovoice/speaker-diarization-benchmark/blob/c71bf73842acbf44d22e65e9f16d460df558cc87/engine.py#L110-L111

**Comment by mrrostam** [comment]
We retested the benchmark with your proposed audio file loading modification, but haven't seen a meaningful impact on the core-hour results for pyannote.
